#esto sirve para modificar valores sin modificar el codigo fuente, es eficaz para cambiar parametros de forma mas rapida

#modifica cantidad de planetas, tamaño de la pantalla y otras cosas
simulation:
  num_bodies: 100
  screen_width: 1200
  screen_height: 800
  time_step: 0.5
  gravity_constant: 0.05

planet:
  mass:
    type: normal #distribucion normal
    mean: 10.0
    stddev: 2.5
    min: 1.0
    max: 20.0
  position:
    type: uniform
    x_min: 0
    x_max: 1200
    y_min: 0
    y_max: 800
  velocity:
    type: uniform
    vx_min: -1.0
    vx_max: 1.0
    vy_min: -1.0
    vy_max: 1.0

visual:
  shapes: ["circle", "square", "triangle"]
  use_random_colors: true
  min_size: 5
  size_scale_factor: 1.5

collisions:
  enable_merging: true

moons:
  enable: true
  max_moons_per_planet: 2
  moon_mass_ratio: 0.1
